# Generated by Django 6.0.5 on 2026-05-16 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('PUBLISHED', 'published'), ('DRAFTED', 'drafted')], default='DRAFTED', max_length=9, verbose_name='status'),
        ),
    ]
