# Generated by Django 6.0.5 on 2026-05-16 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_comment_commentreply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentReply',
        ),
    ]
